### ISSUE TITLE
ms-dos-7.10 image: EMM386 crash on boot

### ISSUE THREAD

**Issue by clobber** [palmercluff/qemu-images#1]
Using the ms-dos-7.10.qcow2 image and executing:

`qemu-system-i386 -hda ms-dos-7.10.qcow2`

MS-DOS 7.10 (CDU) crashes on boot with a strange EMM386 error:
![screen shot 2018-08-29 at 12 49 32 am](https://user-images.githubusercontent.com/1303132/44768202-302a8500-ab26-11e8-9c09-6a81ed02b2ea.png)

I've passed various amounts of memory with the `-m` switch and no change. Thought perhaps there is a problem with the configuration for this image. Specs are:

QEMU 3.0.0, installed via `brew install qemu`
OS X 10.11.6
MacBook Pro (Mid 2009)

I haven't yet tested on my newer machine running macOS 10.13 but I assume the results are the same.

**Comment by palmercluff** [comment]
@clobber Thanks for opening up the first issue for this repo!

I'm sorry you are having issues with this. From my testing, it appears QEMU 3.0.0 breaks trying to run this image. I just tested QEMU 2.12.0, and it appears this is the last stable version of QEMU where it will successfully run this MS-DOS image. Older versions of QEMU also run it successfully.

I hope that QEMU fixes this issue in their updates to v3.0 of QEMU, as I don't think it is an issue with the image. If you want, I can give you the .ISO I used to create the image, but for now if you downgrade from v3.0.0 to v2.12.0 it should be resolved. Let me know if this resolves the issue.

**Comment by clobber** [comment]
Thank you for verifying! Unfortunately it will be a pain for me to downgrade to QEMU 2.x so I will have to wait until if/when this problem is fixed in v3.x. As an aside, I noticed I cannot install FreeDOS 1.2 via the standard instructions either. After some time during the "gathering information" step it will fail with: 
![screen shot 2018-08-29 at 1 15 32 am](https://user-images.githubusercontent.com/1303132/44799835-845f5480-ab7a-11e8-882f-8316ace84587.png)

So it seems there may have been quite a few issues/regressions in QEMU 3.0.0. Anyway, since neither of these are your problem I will close this issue. Maybe it will help somebody else that runs into the same trouble.

**Comment by palmercluff** [comment]
Hmmm, it's starting to look like a lot of these are going to be broken as per your testing with v3.0.0... but I do greatly appreciate that you are trying these images out, so thank you.

If these are not fixed in upcoming QEMU releases, it looks like I may need to put a disclaimer on the README: "Images known to work with QEMU v2.12.0 and below".

**Comment by clobber** [comment]
I should clarify: I was able to run the FreeDOS 1.2 image here, just not able to create my own install from their ISO.

**Comment by palmercluff** [comment]
Oh, I see. Well, I guess we could say this is good news and bad news then. I really hope QEMU fixes this. I guess with the 2.0 to 3.0 version change, there are a lot of differences in the QEMU build...
