### ISSUE TITLE
Debian 8 and 9?

### ISSUE THREAD

**Issue by zedtux** [palmercluff/qemu-images#2]
Hey @palmercluff,

Thank you very much for this awesome repo 👍.

Is it plan to add the Debian 8 and 9 images?

I'm developing the [Douane](https://gitlab.com/douaneapp/Douane) project, and I'm looking for a way to automatise the testing of the project, and QEMU + your images looks like a nice couple to me.

I'd like to test Douane against the previous, the current and the next version of Debian (and later Ubuntu too) so I'm looking for QEMU images.

**Comment by palmercluff** [comment]
Hey @zedtux, great question.

I wasn't planning on adding Debian 8 or 9 until they have surpassed their LTS, but this wouldn't stop you from creating your own :)

**Comment by zedtux** [comment]
Thank you @palmercluff for your comment.

Actually I'm looking for a wait to save time on testing my app, so building those images by my self wouldn't help me, that's why I was enthusiast about this repo.
