### ISSUE TITLE
How to set up drive Z: ?

### ISSUE THREAD

**Issue by philiprhoades** [palmercluff/qemu-images#3]
Palmer,

Thanks for this! - I have thought of a new use for some old DOS software we developed in the '80s but I need to get the old stuff working first - is it possible to set up a drive Z: - that is just the Linux directory from where I start the qemu program?

Regards,
Phil.

**Comment by mgarcia-org** [comment]
qemu-system-i386 -m 16 -hda ms-dos-7.10.qcow2 -drive file=fat:rw:./src

where src is your linux folder, DOS will see it as D: drive

**Comment by philiprhoades** [comment]
Ah! - thanks for that!

**Comment by palmercluff** [comment]
Thanks @philiprhoades for the kind words.

And thanks @mgarcia-org for commenting. Closing issue.
